sudo: false
language: python
matrix:
    include:
        - python: 2.7
          dist: xenial
        - python: 3.4
          dist: xenial
        - python: 3.5
          dist: xenial
        - python: 3.6
          dist: xenial
        - python: 3.7
          dist: xenial
        - python: 3.8
          dist: xenial
        - python: nightly
          dist: bionic
script: python setup.py test
